name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write # Allow the workflow to read and write repository contents (e.g., for commit status updates)

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (LTS recommended)
        uses: actions/setup-node@v4
        with:
          node-version: '23'   # use LTS if you don't need v23

      - name: Frontend Syntax Check
        run: |
          cd frontend
          find . \( -name "*.js" -o -name "*.jsx" \) -exec node --check {} +

      - name: Backend Syntax Check
        run: |
         cd backend
         python -m compileall . 

  gitleaks-scan:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v2

      - name: Gitleaks Scan
        run: |
          gitleaks detect --source ./frontend --exit-code 1
          gitleaks detect --source ./backend --exit-code 1

  trivy_fs_scan:
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb stable main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy Scan
        run: |
          trivy fs --severity CRITICAL,HIGH --ignore-unfixed .

